### ISSUE TITLE
NPE on InputStream.read(byte[]) with Android API 28

### ISSUE THREAD

**Issue by Hazae41** [ipfs/java-ipfs-http-client#125]
I get this while using `IPFS("127.0.0.1", 5001)` on `Android API 28` app and `Android 9.0 `phone
When using `Android API 27` it works fine

```
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
W/System.err:     at io.ipfs.api.IPFS.readFully(IPFS.java:655)
        at io.ipfs.api.IPFS.get(IPFS.java:591)
        at io.ipfs.api.IPFS.retrieve(IPFS.java:571)
        at io.ipfs.api.IPFS.retrieveAndParse(IPFS.java:553)
        at io.ipfs.api.IPFS.version(IPFS.java:501)
        at io.ipfs.api.IPFS.<init>(IPFS.java:61)
        at io.ipfs.api.IPFS.<init>(IPFS.java:44)
```

Thanks

**Comment by ianopolous** [comment]
It looks like you have a null input stream. I can't support android directly, but I'm happy to accept patches fixing issues for android.

**Comment by fCorleone** [comment]
@hazae41 @ianopolous I met with the same problem here and I think I have found the reason as well as the solution.
The reason for this problem is that an IOException occurs in function 
```
private static byte[] get(URL target) throws IOException {
```
at line 665 in the file IPFS.java.
The IOException is caught by the catch block, however, there is no ErrorStream in the variable conn:
```
String err = new String(readFully(conn.getErrorStream()));
```

So what is the IOException exactly? I try to delete the catch block of this IOException and the log give some error information like:

**java.io.IOException: Cleartext HTTP traffic to 127.0.0.1 not permitted**

This is because Google only permit the url connection in a safe mode in new Android app(API after version 27). That explains why the API before version 27 works.

The solution is to use "https" instead of "http" or use the API before 27 please.
