### ISSUE TITLE
How to get a list of files through java-ipfs-api ipfs

### ISSUE THREAD

**Issue by MihaiWong** [ipfs/java-ipfs-http-client#133]
HI，How do I get a list of files?

**Comment by Clay-Ferguson** [comment]
https://github.com/Clay-Ferguson/SubNode.org/blob/master/src/main/java/com/meta64/mobile/service/IPFSService.java

basically the answer is that the 'links' in the MerkleNode points to all the children. See getChildren() in the above file, which is my current experimenting with IPFS. I'm writing an IPFS Browser.

My biggest issue is getting MIME data. That's where i'm currently stuck. I think the current solution they are using might be to "detect" the mime from the stream of bytes, but frankly that is not a good solution.

**Comment by Clay-Ferguson** [comment]
regarding the "cat" function, it looks like it *does* set the Content-Type, in the response, which is good, but it does mean you have to read all the data before you can know the type of the data. Seems like there should be a way to know the 'mime' type of some data without having to actually read it. Regarding this project (java-ipfs-http-client) i'll submit a pull request for a change that allows the headers to be sent back to the  calling function.

**Comment by MihaiWong** [comment]
thanks @Clay-Ferguson  
I can get a list of files, but it seems that I can't get the file directory under the root directory.
I want to get all the files and folders in the root directory, but there seems to be no corresponding method.

**Comment by Clay-Ferguson** [comment]
I think i answered /api/v0/objects when you were really asking about the 'files' api. So that was wrong by me (I'm just learning), but remember the IPFS system isn't reading any folders 'live'. So if you want any folder (including some root) someone would have needed to first ADD that root folder as an IPFS node, and then you would need to know the DAG hash they got back from that load. And the hash of a folder would require scanning the ENTIRE directory subgraph of that entire filesystem, so i'm not sure that's something really ever contemplated, but definitely possible.

**Comment by MihaiWong** [comment]
Thanks for your answer @Clay-Ferguson 
I will try it
